version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flaskapp'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3340:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  
  app:
    container_name: flask_web
    build: .
    ports:
      - '5004:5000'
    depends_on:
      - db

volumes:
  mysql_data: {}