version: '3.8'

services:
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flaskapp'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  
  app:
    container_name: flask_web
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db